[colors.primary]
background = "#000000"

[font]
normal = { family = "CaskaydiaMono Nerd Font Mono", style = "Regular" }
size = 15.9

[window]
# decorations = "None"
opacity = 0.95
# blur = true

[colors]
selection = { background = "#ffffff" }

[cursor]
style = { blinking = "Off" }
vi_mode_style = { shape = "Block", blinking = "Off" }

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
    { key = "[", mods = "Alt", action = "ToggleViMode" },
    { key = "f", mode = "Vi|~Search", action = "InlineSearchForward" },
    { key = "t", mode = "Vi|~Search", action = "InlineSearchBackward" },
    { key = "0", mods = "Shift", mode = "Vi|~Search", action = "First" },
    { key = "$", mode = "Vi|~Search", action = "Last" },
    { key = "b", mode = "Vi|~Search", action = "WordLeft" },
    { key = "w", mode = "Vi|~Search", action = "WordRight" },
    { key = "e", mode = "Vi|~Search", action = "WordRightEnd" },
]
